spring:
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testOath2?serverTimezone=UTC
    username: root
    password: 123456
#    hikari: # springboot 2.0 整合了hikari ,据说这是目前性能最好的java数据库连接池
#      username: root
#      password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启都会新建表
    show-sql: true
  main:
    allow-bean-definition-overriding: true


  jackson:
    serialization:
      INDENT_OUTPUT: true
  data.mongodb:
    host: localhost
    port: 27017
    database: springboot

# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"

# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG